import { useEffect, useState } from 'react'
import StationSelector from '../components/StationSelector.jsx'
import api from '../services/api.js'
import { Activity, Clock, TrendingUp, RefreshCw, Sparkles } from 'lucide-react'

const PEAK_TIMES = [
  { period: 'Morning Peak', time: '8:00 AM – 10:00 AM', level: 'High', color: 'red' },
  { period: 'Midday Off-Peak', time: '10:00 AM – 4:00 PM', level: 'Moderate', color: 'yellow' },
  { period: 'Evening Peak', time: '6:00 PM – 8:00 PM', level: 'High', color: 'red' },
  { period: 'Night Off-Peak', time: '8:00 PM – 11:00 PM', level: 'Low', color: 'green' },
]

const LEVEL_STYLE = {
  High:     'bg-red-50 text-red-700 border-red-200',
  Moderate: 'bg-amber-50 text-amber-700 border-amber-200',
  Low:      'bg-green-50 text-green-700 border-green-200',
}

export default function DemandInsights() {
  const [stations, setStations] = useState([])
  const [networkDemand, setNetworkDemand] = useState(null)
  const [networkLoading, setNetworkLoading] = useState(true)

  const [selectedStation, setSelectedStation] = useState('')
  const [stationDemand, setStationDemand] = useState(null)
  const [stationLoading, setStationLoading] = useState(false)

  useEffect(() => {
    api.getStations().then(({ data }) => data && setStations(data))
    loadNetworkDemand()
  }, [])

  function loadNetworkDemand() {
    setNetworkLoading(true)
    api.getDemand().then(({ data }) => {
      setNetworkDemand(data)
      setNetworkLoading(false)
    })
  }

  function loadStationDemand(code) {
    if (!code) {
      setStationDemand(null)
      return
    }
    setStationLoading(true)
    api.getDemandPrediction(code).then(({ data }) => {
      setStationDemand(data)
      setStationLoading(false)
    })
  }

  function handleStationChange(code) {
    setSelectedStation(code)
    loadStationDemand(code)
  }

  const selectedStationName = stations.find((s) => s.station_code === selectedStation)?.station_name

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 py-10">
      <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mb-8">
        <div>
          <h1 className="font-display font-semibold text-2xl sm:text-3xl">Demand Insights</h1>
          <p className="text-muted text-sm mt-1">
            AI-powered demand predictions based on time-of-day signals.
          </p>
        </div>
        <button
          onClick={loadNetworkDemand}
          disabled={networkLoading}
          className="shrink-0 flex items-center gap-2 text-sm font-medium px-4 py-2 rounded-lg border border-border hover:bg-surface disabled:opacity-50"
        >
          <RefreshCw size={14} className={networkLoading ? 'animate-spin' : ''} />
          Refresh Prediction
        </button>
      </div>

      {/* AI Disclaimer */}
      <div className="rounded-xl2 border border-purple-200 bg-purple-50 p-4 mb-8 flex items-start gap-3">
        <Sparkles size={16} className="text-purple-600 shrink-0 mt-0.5" />
        <div>
          <p className="text-sm font-semibold text-purple-800">AI Prediction — Not Live Data</p>
          <p className="text-xs text-purple-700/80 mt-0.5">
            Demand predictions are generated by AI based on time-of-day and day-of-week signals.
            They are estimates, not live passenger counts or official BMRCL ridership data.
          </p>
        </div>
      </div>

      {/* Network demand prediction */}
      <section className="mb-8">
        <h2 className="font-display font-semibold text-xl mb-4">Current Network Demand</h2>

        {networkLoading && (
          <div className="rounded-xl2 border border-border bg-white p-5">
            <div className="flex items-center gap-2 text-sm text-muted">
              <RefreshCw size={14} className="animate-spin" />
              Generating network demand prediction...
            </div>
          </div>
        )}

        {!networkLoading && networkDemand && (
          <div className="rounded-xl2 border border-purple-200 bg-gradient-to-br from-purple-50 to-white p-5 shadow-soft">
            <p className="text-sm leading-relaxed">{networkDemand.prediction}</p>
            {networkDemand.signals && (
              <div className="mt-4 pt-4 border-t border-purple-100 grid grid-cols-2 sm:grid-cols-3 gap-3">
                <SignalTile label="Period" value={networkDemand.signals.peak_period} />
                <SignalTile label="Day" value={networkDemand.signals.day_of_week} />
                <SignalTile
                  label="Peak Hour"
                  value={networkDemand.signals.is_peak_hour ? 'Yes' : 'No'}
                />
              </div>
            )}
            <p className="text-[11px] text-purple-700/60 mt-3">{networkDemand.disclaimer}</p>
          </div>
        )}
      </section>

      {/* Peak hour reference */}
      <section className="mb-8">
        <h2 className="font-display font-semibold text-xl mb-4">Peak Hour Reference</h2>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4">
          {PEAK_TIMES.map((p) => (
            <div
              key={p.period}
              className={`rounded-xl2 border p-4 ${LEVEL_STYLE[p.level] || 'bg-surface border-border'}`}
            >
              <p className="font-semibold text-sm">{p.period}</p>
              <p className="text-xs mt-1 opacity-80">{p.time}</p>
              <span className={`inline-block mt-2 text-[11px] font-bold uppercase tracking-wide px-2 py-0.5 rounded-full border ${LEVEL_STYLE[p.level]}`}>
                {p.level}
              </span>
            </div>
          ))}
        </div>
        <p className="text-xs text-muted mt-3">
          Peak hour patterns are general estimates. Actual demand varies by line and day.
        </p>
      </section>

      {/* Station demand prediction */}
      <section className="mb-8">
        <h2 className="font-display font-semibold text-xl mb-4">Station Demand Prediction</h2>
        <div className="rounded-xl2 border border-border bg-white p-5 shadow-soft">
          <div className="max-w-sm mb-5">
            <StationSelector
              label="Select a Station"
              stations={stations}
              value={selectedStation}
              onChange={handleStationChange}
              placeholder="Choose a metro station"
            />
          </div>

          {stationLoading && (
            <div className="flex items-center gap-2 text-sm text-muted">
              <RefreshCw size={14} className="animate-spin" />
              Generating station demand prediction...
            </div>
          )}

          {!stationLoading && stationDemand && (
            <div>
              <div className="flex items-center gap-2 mb-3">
                <Sparkles size={14} className="text-purple-600" />
                <span className="text-xs font-bold uppercase tracking-wide text-purple-700">
                  AI PREDICTION
                </span>
              </div>
              <p className="text-sm leading-relaxed">{stationDemand.prediction}</p>
              {stationDemand.signals && (
                <div className="mt-4 pt-4 border-t border-border grid grid-cols-2 sm:grid-cols-3 gap-3">
                  <SignalTile label="Period" value={stationDemand.signals.peak_period} />
                  <SignalTile label="Day" value={stationDemand.signals.day_of_week} />
                  <SignalTile
                    label="Weekend"
                    value={stationDemand.signals.is_weekend ? 'Yes' : 'No'}
                  />
                </div>
              )}
              <p className="text-[11px] text-muted mt-3">{stationDemand.disclaimer}</p>
            </div>
          )}

          {!stationLoading && !stationDemand && !selectedStation && (
            <p className="text-sm text-muted">
              Select a station above to see an AI demand prediction.
            </p>
          )}
        </div>
      </section>

      {/* Travel tips */}
      <section>
        <h2 className="font-display font-semibold text-xl mb-4">Travel Tips</h2>
        <div className="grid sm:grid-cols-2 gap-4">
          <TipCard
            icon={Clock}
            title="Avoid Peak Hours"
            tip="Travel before 8 AM or after 10 AM, or between 4 PM and 6 PM for a more comfortable journey."
          />
          <TipCard
            icon={TrendingUp}
            title="Interchange Planning"
            tip="Majestic and RV Road stations are interchanges. Allow extra 4-5 minutes when changing lines."
          />
          <TipCard
            icon={Activity}
            title="Weekend Travel"
            tip="Weekends typically see lower demand than weekday peak hours."
          />
          <TipCard
            icon={Sparkles}
            title="AI Insight"
            tip="Use the chatbot to ask about a specific station or journey — it will factor in the current time."
          />
        </div>
      </section>
    </div>
  )
}

function SignalTile({ label, value }) {
  return (
    <div className="bg-white rounded-lg border border-purple-100 p-2.5">
      <p className="text-[10px] uppercase tracking-wide text-purple-600/70">{label}</p>
      <p className="text-sm font-semibold mt-0.5">{value}</p>
    </div>
  )
}

function TipCard({ icon: Icon, title, tip }) {
  return (
    <div className="rounded-xl2 border border-border bg-white p-5 shadow-soft">
      <div className="flex items-center gap-2 mb-2">
        <span className="w-8 h-8 rounded-lg bg-surface flex items-center justify-center">
          <Icon size={16} />
        </span>
        <h3 className="font-semibold text-sm">{title}</h3>
      </div>
      <p className="text-sm text-muted leading-relaxed">{tip}</p>
    </div>
  )
}
